version: '2'
services:
    gipster-app:
        image: gipster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://gipster-postgresql:5432/gipster
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gipster-postgresql:
        extends:
            file: postgresql.yml
            service: gipster-postgresql
